---
title: "Reproducible Research: Peer Assessment 1"
author: "Matthias Gloel"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r, echo=TRUE}
# I decided to use the base plotting system and try to do the analysis with R core functions so that
# no additional packages need to be installed

df <- read.csv('activity.csv')
````


## What is mean total number of steps taken per day?

```{r, echo=TRUE}
mean_total_steps <- data.frame(tapply(df$steps, df$date, mean))
names(mean_total_steps) <- c('mean_steps')
mean_total_steps$date <- as.Date(rownames(mean_total_steps))
hist(mean_total_steps$mean_steps, main='Histogram of mean total steps', xlab="Mean Total Steps",col="red", ylim=c(0,20))

d1 <- data.frame(tapply(df$steps, df$date, mean))
d2 <- data.frame(tapply(df$steps, df$date, median))
tab <- cbind(d1,d2)
names(tab) <- c('Mean', 'Median')
tab
````

## What is the average daily activity pattern?

```{r, echo=TRUE}
# Remove NA's for line plot
df2 <- subset(df, !is.na(df$steps))

daily_act <- data.frame(tapply(df2$steps, df2$interval, mean))
names(daily_act) <- c('mean_steps')
daily_act$interval <- rownames(daily_act)
plot(daily_act$interval, daily_act$mean_steps, type='l',xlab='Interval',ylab='Mean steps', main='Daily Activity Pattern')

````

## Imputing missing values

```{r, echo=TRUE}
# Number of rows with NA
sum(is.na(df$step))

# Create new dataframe with imputed NA's based on resp. interval mean
df_comp <- df

for(i in 1:nrow(df_comp)){
    if(is.na(df_comp$steps[i])){  
        df_comp$steps[i] <- daily_act$mean_steps[which(daily_act$interval == df_comp$interval[i])][1]
    }
}

# Histogram
mean_total_steps2 <- data.frame(tapply(df_comp$steps, df_comp$date, mean))
names(mean_total_steps2) <- c('mean_steps')
mean_total_steps2$date <- as.Date(rownames(mean_total_steps2))
hist(mean_total_steps2$mean_steps, main='Histogram of mean total steps (NA imputed)', xlab="Mean Total Steps",col="green", ylim=c(0,30))

# Table with Means and Medians
d3 <- data.frame(tapply(df_comp$steps, df_comp$date, mean))
d4 <- data.frame(tapply(df_comp$steps, df_comp$date, median))
tab2 <- cbind(d3,d4)
names(tab2) <- c('Mean', 'Median')
tab2
````

## Are there differences in activity patterns between weekdays and weekends?

```{r, echo=TRUE}
weekdays(as.Date(df$date))
````
